
import './js/script.js';
import './style.scss';

import './img/Диагностика.png';
import './img/Зубные-протезы.png';
import './img/Имплантация.png';
import './img/Лечение-каналов.png';
import './img/Лечение-кариеса.png';
import './img/Ортондонтия.png';
import './img/Отбеливание.png';
import './img/Профессиональная.png';
import './img/Реставрация.png';
import './img/Удаление-зубов.png';
import './img/Установка-виниров.png';
import './img/Установка.png';
import './img/eye.png';
import './img/white-logo.png';
import './img/logo.png';
import './img/backgroung-header.jpg';
import './img/profile1.jpg';
import './img/profile2.jpg';
import './img/profile3.jpg';
import './img/profile4.jpg';
import './img/teeth.jpg';
import './img/profile-feedback.jpg';
import './img/map.jpg';
import './img/geoicon.png';
import './img/plast.png';
